name: Manual Deploy Pipeline

on:
  workflow_dispatch:
    inputs:
      space:
        description: "Select the Cloud Foundry Space"
        required: true
        type: choice
        options:
          - "DEV"
          - "CGI"
          - "INT"
          - "PREPROD"
          - "PROD"

      bg-deploy:
        description: "Run as Blue/Green Deployment?"
        required: true
        default: false
        type: boolean

      git-ref:
        description: "Set the GIT Tag (e.g. 'Release_1.1.3'), Branch (e.g. main) or Commit SHA"
        required: true
        default: "main"
        type: string

jobs:
  cf-deployment:
    name: Deploy to Cloud Foundry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.git-ref }}

      - name: Set up Cloud Foundry
        shell: sh
        run: echo "[WARN] CF Setup Job for ${{ inputs.space }} not connected yet!"

      - name: Deploy via Manifest
        if: ${{ inputs.bg-deploy == false }}
        shell: sh
        run: echo "[WARN] Deploy Job not connected yet!"

      - name: Deploy via Manifest (Blue/Green)
        if: ${{ inputs.bg-deploy == true }}
        shell: sh
        run: echo "[WARN] BG Deploy Job not connected yet!"

  bg-evaluation:
    name: Blue/Green Evaluation
    runs-on: ubuntu-latest
    if: ${{ inputs.bg-deploy == true }}
    needs: cf-deployment
    environment:
      name: blue-green-deployment
    steps:
      - name: Evaluate Deployment
        run: echo "Evaluating deployment in Blue environment."

  cf-continue-bg:
    name: CF Cleanup
    runs-on: ubuntu-latest
    needs: bg-evaluation
    if: ${{ always() && inputs.bg-deploy == true && needs.bg-evaluation.result == 'success' }}
    steps:
      - name: Deploy to Green Environment
        if: ${{ env.decision == 'proceed' }}
        run: echo "Cleanup environment."

  cf-rollback-bg:
    name: CF Rollback
    runs-on: ubuntu-latest
    needs: bg-evaluation
    if: ${{ always() && inputs.bg-deploy == true && needs.bg-evaluation.result != 'success' }}
    steps:
      - name: Deploy to Green Environment
        run: echo "Rollback environment."
